#!/usr/bin/env bash
# FizzBuzz challenge

for((count=1; count <= 100; count++)); do
    if [ $((count%3)) == 0 ] && [ $((count%5)) == 0 ]; then
	echo "FizzBuzz"
	continue
    elif [ $((count%3)) == 0 ]; then
	echo "Fizz"
    elif [ $((count%5)) == 0 ]; then
	echo "Buzz"
    else
	echo $count
    fi
done
