#!/usr/bin/env bash
# Loop 10 times, display "bad luck" and "good luck" on 4th and 8th iteration
count=1

while((count <= 10)); do
    if [ $count == 4 ]; then
	echo "bad luck"
    elif [ $count == 8 ]; then
	echo "good luck"
    else
	echo "Best School"
    fi
    ((count+=1))
done
