#!/usr/bin/env bash
# Loop statement and case
count=1

while((count <= 20)); do
    echo "$count"
    case $count in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
	esac
    ((count+=1))
done
