#!/usr/bin/env bash
# Evaluates school file and print information about it
FILE=./school
if test -e "$FILE"; then
    echo "school file exists"

    # check if file is empth
    if [ -s $FILE ]; then
	echo "school file is not empty"
    else
	echo "school file is empty"
    fi

    # check if file is a regular file
    if test -f "$FILE"; then
	echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
