#!/usr/bin/env bash
# Install nginx
apt-get update
apt-get install -y nginx

# Set nginx user to nginx
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Set permissions for nginx user
chown -R nginx:nginx /var/lib/nginx

# Listen on all active IPs on port 8080
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default
